---
################################################
# LOCAL
################################################
spring:
  config:
    activate:
      on-profile: lcl


---
################################################
# DEV
################################################
spring:
  config:
    activate:
      on-profile: dev

---
################################################
# STG
################################################
spring:
  config:
    activate:
      on-profile: stg

---
################################################
# PRD
################################################
spring:
  config:
    activate:
      on-profile: prd

